// web/src/lib/componentes/FilaMovimiento.svelte
<script lang="ts">
	import type { Movimiento } from '$lib/datos/tipos';
	import { colorCategoria, nombreCategoria } from '$lib/categorias';
	import { clp, fecha, NOMBRES_ESTADO, nombreBanco } from '$lib/formato';

	let { m, conFecha = false }: { m: Movimiento; conFecha?: boolean } = $props();

	const entrada = $derived(m.monto > 0);
	const neutro = $derived(m.tipo_flujo === 'transferencia_interna' || m.tipo_flujo === 'pago_deuda');
</script>

<li class="fila">
	<span class="marca" style:--c={colorCategoria(m.categoria)} aria-hidden="true">
		{(m.comercio ?? m.glosa).slice(0, 1).toUpperCase()}
	</span>
	<div class="cuerpo">
		<p class="titulo">{m.comercio ?? m.glosa}</p>
		<p class="meta">
			{#if conFecha}<span class="num">{fecha(m.fecha_imputacion)}</span> ·{/if}
			{nombreCategoria(m.categoria)} · {m.producto_nombre}
			<span class="banco">{nombreBanco(m.banco)}</span>
		</p>
		{#if m.cuotas_total || m.fecha !== m.fecha_imputacion || m.estado === 'no_facturado' || m.estado === 'pendiente'}
			<p class="insignias">
				{#if m.cuotas_total}<span class="insignia acento num">Cuota {m.cuota_actual}/{m.cuotas_total}</span>{/if}
				{#if m.fecha !== m.fecha_imputacion}<span class="insignia num">Compra {fecha(m.fecha)}</span>{/if}
				{#if m.estado === 'no_facturado' || m.estado === 'pendiente'}<span class="insignia aviso">{NOMBRES_ESTADO[m.estado]}</span>{/if}
			</p>
		{/if}
	</div>
	<div class="monto">
		<p class="num valor" class:positivo={entrada && !neutro} class:neutro>{clp(m.monto, true)}</p>
		{#if m.monto_total_compra}<p class="tenue num">de {clp(m.monto_total_compra)}</p>{/if}
	</div>
</li>

<style>
	.fila {
		display: flex;
		align-items: flex-start;
		gap: 12px;
		padding: 12px 0;
		border-bottom: 1px solid var(--borde);
	}

	.fila:last-child {
		border-bottom: 0;
	}

	.marca {
		display: grid;
		place-items: center;
		flex: none;
		width: 36px;
		height: 36px;
		border-radius: 11px;
		background: color-mix(in srgb, var(--c) 20%, var(--superficie));
		box-shadow: inset 0 0 0 1.5px color-mix(in srgb, var(--c) 55%, transparent);
		color: var(--texto);
		font-weight: 700;
		font-size: 0.85rem;
	}

	.cuerpo {
		flex: 1;
		min-width: 0;
	}

	.titulo {
		font-weight: 600;
		font-size: 0.93rem;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.meta {
		font-size: 0.78rem;
		color: var(--texto-3);
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.banco::before {
		content: '· ';
	}

	.insignias {
		display: flex;
		flex-wrap: wrap;
		gap: 4px;
		margin-top: 4px;
	}

	.monto {
		text-align: right;
		flex: none;
	}

	.valor {
		font-weight: 650;
		font-size: 0.93rem;
	}

	.neutro {
		color: var(--texto-2);
	}

	.tenue {
		font-size: 0.72rem;
	}
</style>

// app/src/componentes/FilaMovimiento.tsx
import { memo } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import type { Movimiento } from '@/datos/tipos';
import { nombreCategoria } from '@/lib/categorias';
import { clp, fecha, fechasMovimiento, NOMBRES_ESTADO, nombreBanco } from '@/lib/formato';
import { useEstilos, useTema } from '@/tema/tema';
import { conAlfa, mezclar, NUMEROS, type Tema } from '@/tema/tokens';
import { Insignia } from './base';

export const FilaMovimiento = memo(function FilaMovimiento({ m, conFecha, ultima }: { m: Movimiento; conFecha?: boolean; ultima?: boolean }) {
	const t = useTema();
	const e = useEstilos(estilos);
	const color = t.cat(m.categoria);
	const entrada = m.monto > 0;
	const neutro = m.tipo_flujo === 'transferencia_interna' || m.tipo_flujo === 'pago_deuda';
	const titulo = m.comercio ?? m.glosa;
	const pendiente = m.estado === 'no_facturado' || m.estado === 'pendiente';
	const f = fechasMovimiento(m);
	return (
		<View style={[e.fila, ultima && { borderBottomWidth: 0 }]} role="listitem">
			<View style={[e.marca, { backgroundColor: mezclar(color, t.c.superficie, 20), boxShadow: `inset 0px 0px 0px 1.5px ${conAlfa(color, 0.55)}` }]} aria-hidden>
				<Text style={e.inicial}>{titulo.slice(0, 1).toUpperCase()}</Text>
			</View>
			<View style={e.cuerpo}>
				<Text style={e.titulo} numberOfLines={1}>
					{titulo}
				</Text>
				<Text style={e.meta} numberOfLines={1}>
					{conFecha ? `${fecha(f.mostrada)} · ` : ''}
					{nombreCategoria(m.categoria)} · {m.producto_nombre} · {nombreBanco(m.banco)}
				</Text>
				{m.cuotas_total || f.nota || pendiente ? (
					<View style={e.insignias}>
						{m.cuotas_total ? <Insignia clase="acento" texto={`Cuota ${m.cuota_actual}/${m.cuotas_total}`} /> : null}
						{f.nota ? <Insignia texto={f.nota} /> : null}
						{pendiente ? <Insignia clase="aviso" texto={NOMBRES_ESTADO[m.estado]} /> : null}
					</View>
				) : null}
			</View>
			<View style={e.monto}>
				<Text style={[e.valor, entrada && !neutro && { color: t.c.positivo }, neutro && { color: t.c.texto2 }]}>{clp(m.monto, true)}</Text>
				{m.monto_total_compra ? <Text style={e.total}>de {clp(m.monto_total_compra)}</Text> : null}
			</View>
		</View>
	);
});

function estilos({ c }: Tema) {
	return StyleSheet.create({
		fila: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: c.borde },
		marca: { width: 36, height: 36, borderRadius: 11, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
		inicial: { color: c.texto, fontWeight: '700', fontSize: 13.6 },
		cuerpo: { flex: 1, minWidth: 0 },
		titulo: { fontWeight: '600', fontSize: 14.9, color: c.texto },
		meta: { fontSize: 12.5, color: c.texto3 },
		insignias: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 4 },
		monto: { alignItems: 'flex-end', flexShrink: 0 },
		valor: { fontWeight: '600', fontSize: 14.9, fontVariant: NUMEROS, color: c.texto },
		total: { fontSize: 11.5, color: c.texto3, fontVariant: NUMEROS }
	});
}
