// web/src/lib/componentes/Navegacion.svelte
<script lang="ts">
	import { page } from '$app/state';
	import Icono from './Icono.svelte';

	let { modoDemo, email, nombre }: { modoDemo: boolean; email: string | null; nombre: string | null } = $props();

	const ITEMS = [
		{ href: '/', texto: 'Resumen', corto: 'Resumen', icono: 'resumen' },
		{ href: '/mes', texto: 'Mes', corto: 'Mes', icono: 'plan' },
		{ href: '/deudas', texto: 'Deudas', corto: 'Deudas', icono: 'deudas' },
		{ href: '/carro', texto: 'Carro', corto: 'Carro', icono: 'sobre' },
		{ href: '/movimientos', texto: 'Movimientos', corto: 'Movimientos', icono: 'movimientos' },
		{ href: '/pagos-fijos', texto: 'Pagos fijos', corto: 'Fijos', icono: 'fijos' },
		{ href: '/anotar', texto: 'Sobres', corto: 'Sobres', icono: 'presupuestos' },
		{ href: '/diario', texto: 'Diario', corto: 'Diario', icono: 'diario' },
		{ href: '/categorias', texto: 'Categorías', corto: 'Categorías', icono: 'categorias' }
	];
	const PRINCIPALES = ITEMS.slice(0, 3);
	const EXTRA = ITEMS.slice(4);

	let menuAbierto = $state(false);
	const activo = (href: string) => (href === '/' ? page.url.pathname === '/' : page.url.pathname.startsWith(href));
	const extraActivo = $derived(EXTRA.some((i) => activo(i.href)));

	$effect(() => {
		page.url.pathname;
		menuAbierto = false;
	});
</script>

<aside class="lateral" aria-label="Navegación principal">
	<a class="marca" href="/">
		<span class="logo" aria-hidden="true"><Icono nombre="tendencia" tam={18} grosor={2.4} /></span>
		<span>Cuotazo</span>
	</a>
	<nav>
		{#each ITEMS as item (item.href)}
			<a href={item.href} class:activo={activo(item.href)} class:destacado={item.href === '/carro'} aria-current={activo(item.href) ? 'page' : undefined}>
				<Icono nombre={item.icono} tam={19} />
				<span>{item.texto}</span>
			</a>
		{/each}
	</nav>
	<div class="pie">
		{#if modoDemo}
			<div class="demo">
				<strong>Modo demostración</strong>
				<span>Datos sintéticos, no reales.</span>
			</div>
		{:else if email}
			<div class="cuenta">
				<span class="avatar" aria-hidden="true">{(nombre ?? email)[0].toUpperCase()}</span>
				<span class="correo" title={email}>{nombre ?? email}</span>
			</div>
			<form method="POST" action="/salir">
				<button class="boton fantasma salir" type="submit"><Icono nombre="salir" tam={17} /> Cerrar sesión</button>
			</form>
		{/if}
	</div>
</aside>

<nav class="inferior" aria-label="Navegación principal">
	{#each PRINCIPALES.slice(0, 2) as item (item.href)}
		<a href={item.href} class:activo={activo(item.href)} aria-current={activo(item.href) ? 'page' : undefined}>
			<Icono nombre={item.icono} tam={22} />
			<span>{item.corto}</span>
		</a>
	{/each}
	<a href="/carro" class="anotar" class:activo={activo('/carro')} aria-current={activo('/carro') ? 'page' : undefined} aria-label="Carro de compras">
		<span class="mas-grande"><Icono nombre="mas_simple" tam={26} grosor={2.6} /></span>
	</a>
	{#each PRINCIPALES.slice(2) as item (item.href)}
		<a href={item.href} class:activo={activo(item.href)} aria-current={activo(item.href) ? 'page' : undefined}>
			<Icono nombre={item.icono} tam={22} />
			<span>{item.corto}</span>
		</a>
	{/each}
	<button
		type="button"
		class:activo={extraActivo || menuAbierto}
		aria-expanded={menuAbierto}
		aria-controls="menu-mas"
		onclick={() => (menuAbierto = !menuAbierto)}
	>
		<Icono nombre="mas" tam={22} grosor={2.6} />
		<span>Más</span>
	</button>
</nav>

{#if menuAbierto}
	<button class="velo" type="button" aria-label="Cerrar menú" onclick={() => (menuAbierto = false)}></button>
	<div class="hoja" id="menu-mas" role="menu">
		{#each EXTRA as item (item.href)}
			<a role="menuitem" href={item.href} class:activo={activo(item.href)}>
				<Icono nombre={item.icono} tam={20} />
				<span>{item.texto}</span>
			</a>
		{/each}
		{#if modoDemo}
			<p class="nota">Modo demostración · datos sintéticos</p>
		{:else if email}
			<form method="POST" action="/salir">
				<button role="menuitem" type="submit"><Icono nombre="salir" tam={20} /><span>Cerrar sesión</span></button>
			</form>
			<p class="nota">{email}</p>
		{/if}
	</div>
{/if}

<style>
	.lateral {
		display: none;
	}

	.inferior {
		position: fixed;
		inset: auto 0 0 0;
		z-index: 30;
		display: grid;
		grid-template-columns: repeat(5, 1fr);
		height: calc(var(--nav-alto) + env(safe-area-inset-bottom));
		padding-bottom: env(safe-area-inset-bottom);
		background: color-mix(in srgb, var(--superficie) 88%, transparent);
		backdrop-filter: saturate(1.6) blur(16px);
		-webkit-backdrop-filter: saturate(1.6) blur(16px);
		border-top: 1px solid var(--borde);
	}

	.inferior a,
	.inferior button {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 3px;
		font-size: 0.68rem;
		font-weight: 600;
		color: var(--texto-3);
		background: none;
		border: 0;
		padding: 0;
		cursor: pointer;
		position: relative;
	}

	.inferior .activo {
		color: var(--acento-tinta);
	}

	.inferior .anotar::before {
		display: none;
	}

	.mas-grande {
		display: grid;
		place-items: center;
		width: 52px;
		height: 52px;
		margin-top: -18px;
		border-radius: 18px;
		background: var(--acento);
		color: var(--acento-texto);
		box-shadow: var(--sombra-alta);
		border: 3px solid var(--fondo);
	}

	.inferior .activo::before {
		content: '';
		position: absolute;
		top: 0;
		width: 28px;
		height: 3px;
		border-radius: 0 0 3px 3px;
		background: var(--acento);
	}

	.velo {
		position: fixed;
		inset: 0;
		z-index: 31;
		background: rgb(0 0 0 / 0.3);
		border: 0;
	}

	.hoja {
		position: fixed;
		left: 12px;
		right: 12px;
		bottom: calc(var(--nav-alto) + env(safe-area-inset-bottom) + 10px);
		z-index: 32;
		background: var(--superficie);
		border: 1px solid var(--borde);
		border-radius: 18px;
		box-shadow: var(--sombra-alta);
		padding: 8px;
		display: flex;
		flex-direction: column;
	}

	.hoja a,
	.hoja button {
		display: flex;
		align-items: center;
		gap: 12px;
		padding: 13px 12px;
		border-radius: 12px;
		color: var(--texto);
		font-weight: 550;
		background: none;
		border: 0;
		width: 100%;
		text-align: left;
		cursor: pointer;
	}

	.hoja a.activo {
		background: var(--acento-suave);
		color: var(--acento-tinta);
	}

	.nota {
		font-size: 0.78rem;
		color: var(--texto-3);
		padding: 8px 12px 4px;
		border-top: 1px solid var(--borde);
		margin-top: 4px;
	}

	@media (min-width: 960px) {
		.inferior,
		.hoja,
		.velo {
			display: none;
		}

		.lateral {
			position: sticky;
			top: 0;
			height: 100vh;
			display: flex;
			flex-direction: column;
			gap: 24px;
			padding: 22px 14px;
			border-right: 1px solid var(--borde);
			background: var(--superficie);
		}

		.marca {
			display: flex;
			align-items: center;
			gap: 10px;
			color: var(--texto);
			font-weight: 700;
			font-size: 1.05rem;
			letter-spacing: -0.02em;
			padding: 0 8px;
		}

		.logo {
			display: grid;
			place-items: center;
			width: 32px;
			height: 32px;
			border-radius: 10px;
			background: var(--acento);
			color: var(--acento-texto);
		}

		nav {
			display: flex;
			flex-direction: column;
			gap: 2px;
		}

		nav a {
			display: flex;
			align-items: center;
			gap: 12px;
			padding: 10px 12px;
			border-radius: 11px;
			color: var(--texto-2);
			font-weight: 550;
			font-size: 0.93rem;
		}

		nav a:hover {
			background: var(--superficie-2);
			color: var(--texto);
		}

		nav a.destacado {
			margin: 6px 0;
			border: 1px dashed color-mix(in srgb, var(--acento) 55%, transparent);
			color: var(--acento-tinta);
		}

		nav a.activo {
			background: var(--acento-suave);
			color: var(--acento-tinta);
		}

		.pie {
			margin-top: auto;
			display: flex;
			flex-direction: column;
			gap: 8px;
		}

		.demo {
			display: flex;
			flex-direction: column;
			padding: 12px;
			border-radius: 12px;
			background: var(--aviso-suave);
			color: var(--aviso);
			font-size: 0.8rem;
		}

		.cuenta {
			display: flex;
			align-items: center;
			gap: 10px;
			padding: 0 8px;
			min-width: 0;
		}

		.avatar {
			display: grid;
			place-items: center;
			flex: none;
			width: 30px;
			height: 30px;
			border-radius: 50%;
			background: var(--superficie-3);
			font-weight: 700;
			font-size: 0.8rem;
		}

		.correo {
			font-size: 0.85rem;
			overflow: hidden;
			text-overflow: ellipsis;
			white-space: nowrap;
		}

		.salir {
			width: 100%;
			justify-content: flex-start;
			color: var(--texto-2);
		}
	}
</style>

// app/src/componentes/Navegacion.tsx
import { Link, usePathname, type Href } from 'expo-router';
import { useEffect, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { salir } from '@/datos/auth';
import { useEstilos, useTema } from '@/tema/tema';
import type { Tema } from '@/tema/tokens';
import { Icono, type NombreIcono } from './Icono';
import { ALTO_NAV } from './Pagina';

interface Item {
	href: string;
	texto: string;
	icono: NombreIcono;
}

const ITEMS: Item[] = [
	{ href: '/', texto: 'Resumen', icono: 'resumen' },
	{ href: '/diario', texto: 'Diario', icono: 'diario' },
	{ href: '/categorias', texto: 'Categorías', icono: 'categorias' },
	{ href: '/deudas', texto: 'Deudas', icono: 'deudas' },
	{ href: '/presupuestos', texto: 'Alertas', icono: 'campana' },
	{ href: '/plan', texto: 'Plan', icono: 'plan' },
	{ href: '/movimientos', texto: 'Movimientos', icono: 'movimientos' }
];

// En móvil el Plan y las alertas quedan a un toque; el resto va en "Más"
const PRINCIPALES = ['/', '/diario', '/plan', '/presupuestos'].map((h) => ITEMS.find((i) => i.href === h)!);
const EXTRA = ITEMS.filter((i) => !PRINCIPALES.includes(i));

function useActivo() {
	const ruta = usePathname();
	return (href: string) => (href === '/' ? ruta === '/' : ruta.startsWith(href));
}

export function Logo({ tam = 32 }: { tam?: number }) {
	const { c } = useTema();
	return (
		<View style={{ width: tam, height: tam, borderRadius: tam * 0.31, backgroundColor: c.acento, alignItems: 'center', justifyContent: 'center' }}>
			<Icono nombre="tendencia" tam={tam * 0.56} grosor={2.4} color={c.acentoTexto} />
		</View>
	);
}

export function Lateral({ modoDemo, email, nombre }: { modoDemo: boolean; email: string | null; nombre: string | null }) {
	const { c } = useTema();
	const e = useEstilos(estilos);
	const activo = useActivo();
	return (
		<View style={e.lateral} role="navigation" aria-label="Navegación principal">
			<Link href="/" asChild>
				<Pressable style={e.marca} aria-label="Cuotazo, ir al resumen">
					<Logo />
					<Text style={e.marcaTexto}>Cuotazo</Text>
				</Pressable>
			</Link>
			<View style={{ gap: 2 }}>
				{ITEMS.map((it) => {
					const a = activo(it.href);
					return (
						<Link key={it.href} href={it.href as Href} asChild>
							<Pressable aria-current={a ? 'page' : undefined} style={[e.itemLateral, a && { backgroundColor: c.acentoSuave }]}>
								<Icono nombre={it.icono} tam={19} color={a ? c.acentoTinta : c.texto2} />
								<Text style={[e.itemLateralTexto, a && { color: c.acentoTinta }]}>{it.texto}</Text>
							</Pressable>
						</Link>
					);
				})}
			</View>
			<View style={e.pie}>
				{modoDemo ? (
					<View style={e.demo}>
						<Text style={[e.demoTexto, { fontWeight: '700' }]}>Modo demostración</Text>
						<Text style={e.demoTexto}>Datos sintéticos, no reales.</Text>
					</View>
				) : email ? (
					<>
						<View style={e.cuenta}>
							<View style={e.avatar}>
								<Text style={e.avatarTexto}>{(nombre ?? email)[0].toUpperCase()}</Text>
							</View>
							<Text style={e.correo} numberOfLines={1}>
								{nombre ?? email}
							</Text>
						</View>
						<Pressable role="button" onPress={() => salir()} style={e.itemLateral}>
							<Icono nombre="salir" tam={17} color={c.texto2} />
							<Text style={e.itemLateralTexto}>Cerrar sesión</Text>
						</Pressable>
					</>
				) : null}
			</View>
		</View>
	);
}

export function BarraInferior({ modoDemo, email }: { modoDemo: boolean; email: string | null }) {
	const { c } = useTema();
	const e = useEstilos(estilos);
	const activo = useActivo();
	const ruta = usePathname();
	const insets = useSafeAreaInsets();
	const [abierto, setAbierto] = useState(false);
	const extraActivo = EXTRA.some((i) => activo(i.href));

	useEffect(() => setAbierto(false), [ruta]);

	return (
		<>
			<View style={[e.inferior, { height: ALTO_NAV + insets.bottom, paddingBottom: insets.bottom }]} role="navigation" aria-label="Navegación principal">
				{PRINCIPALES.map((it) => {
					const a = activo(it.href);
					return (
						<Link key={it.href} href={it.href as Href} asChild>
							<Pressable style={e.itemInferior} aria-current={a ? 'page' : undefined} aria-label={it.texto}>
								{a ? <View style={e.marcaActiva} /> : null}
								<Icono nombre={it.icono} tam={22} color={a ? c.acentoTinta : c.texto3} />
								<Text style={[e.itemInferiorTexto, a && { color: c.acentoTinta }]}>{it.texto}</Text>
							</Pressable>
						</Link>
					);
				})}
				<Pressable style={e.itemInferior} role="button" aria-expanded={abierto} aria-label="Más" onPress={() => setAbierto(!abierto)}>
					{extraActivo || abierto ? <View style={e.marcaActiva} /> : null}
					<Icono nombre="mas" tam={22} grosor={2.6} color={extraActivo || abierto ? c.acentoTinta : c.texto3} />
					<Text style={[e.itemInferiorTexto, (extraActivo || abierto) && { color: c.acentoTinta }]}>Más</Text>
				</Pressable>
			</View>
			<Modal visible={abierto} transparent animationType="fade" onRequestClose={() => setAbierto(false)}>
				<Pressable style={[StyleSheet.absoluteFill, { backgroundColor: c.velo }]} aria-label="Cerrar menú" onPress={() => setAbierto(false)} />
				<View style={[e.hoja, { bottom: ALTO_NAV + insets.bottom + 10 }]} role="menu">
					{EXTRA.map((it) => {
						const a = activo(it.href);
						return (
							<Link key={it.href} href={it.href as Href} asChild>
								<Pressable role="menuitem" style={[e.itemHoja, a && { backgroundColor: c.acentoSuave }]} onPress={() => setAbierto(false)}>
									<Icono nombre={it.icono} tam={20} color={a ? c.acentoTinta : c.texto} />
									<Text style={[e.itemHojaTexto, a && { color: c.acentoTinta }]}>{it.texto}</Text>
								</Pressable>
							</Link>
						);
					})}
					{modoDemo ? (
						<Text style={e.nota}>Modo demostración · datos sintéticos</Text>
					) : email ? (
						<>
							<Pressable role="menuitem" style={e.itemHoja} onPress={() => salir()}>
								<Icono nombre="salir" tam={20} color={c.texto} />
								<Text style={e.itemHojaTexto}>Cerrar sesión</Text>
							</Pressable>
							<Text style={e.nota} numberOfLines={1}>
								{email}
							</Text>
						</>
					) : null}
				</View>
			</Modal>
		</>
	);
}

function estilos({ c, modo }: Tema) {
	return StyleSheet.create({
		lateral: {
			width: 248,
			height: '100%',
			gap: 24,
			paddingVertical: 22,
			paddingHorizontal: 14,
			borderRightWidth: 1,
			borderRightColor: c.borde,
			backgroundColor: c.superficie
		},
		marca: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, gap: 10 },
		marcaTexto: { color: c.texto, fontWeight: '700', fontSize: 16.8, letterSpacing: -0.34 },
		itemLateral: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 11 },
		itemLateralTexto: { color: c.texto2, fontWeight: '500', fontSize: 14.9 },
		pie: { marginTop: 'auto', gap: 8 },
		demo: { padding: 12, borderRadius: 12, backgroundColor: c.avisoSuave },
		demoTexto: { color: c.aviso, fontSize: 12.8 },
		cuenta: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 8, minWidth: 0 },
		avatar: { width: 30, height: 30, borderRadius: 15, backgroundColor: c.superficie3, alignItems: 'center', justifyContent: 'center' },
		avatarTexto: { fontWeight: '700', fontSize: 12.8, color: c.texto },
		correo: { fontSize: 13.6, color: c.texto, flex: 1 },
		inferior: {
			position: 'absolute',
			left: 0,
			right: 0,
			bottom: 0,
			flexDirection: 'row',
			backgroundColor: modo === 'oscuro' ? 'rgba(21,25,24,0.94)' : 'rgba(255,255,255,0.92)',
			backdropFilter: 'saturate(1.6) blur(16px)',
			borderTopWidth: 1,
			borderTopColor: c.borde
		} as object,
		itemInferior: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3, position: 'relative' },
		itemInferiorTexto: { fontSize: 10.9, fontWeight: '600', color: c.texto3 },
		marcaActiva: { position: 'absolute', top: 0, width: 28, height: 3, borderBottomLeftRadius: 3, borderBottomRightRadius: 3, backgroundColor: c.acento },
		hoja: {
			position: 'absolute',
			left: 12,
			right: 12,
			backgroundColor: c.superficie,
			borderWidth: 1,
			borderColor: c.borde,
			borderRadius: 18,
			boxShadow: c.sombraAlta,
			padding: 8
		},
		itemHoja: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, paddingHorizontal: 12, borderRadius: 12 },
		itemHojaTexto: { color: c.texto, fontWeight: '500', fontSize: 16 },
		nota: { fontSize: 12.5, color: c.texto3, paddingTop: 8, paddingHorizontal: 12, paddingBottom: 4, borderTopWidth: 1, borderTopColor: c.borde, marginTop: 4 }
	});
}
