// web/src/lib/componentes/SelectorMes.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { mesLargo } from '$lib/formato';
	import { mesActual, parametroMes, sumarMeses } from '$lib/fechas';
	import Icono from './Icono.svelte';

	let { mes, minimo, maximo = mesActual() }: { mes: string; minimo?: string; maximo?: string } = $props();

	function enlace(m: string): string {
		const u = new URL(page.url);
		u.searchParams.set('mes', parametroMes(m));
		u.searchParams.delete('p');
		u.searchParams.delete('dia');
		return u.pathname + u.search;
	}

	const anterior = $derived(sumarMeses(mes, -1));
	const siguiente = $derived(sumarMeses(mes, 1));
	const hayAnterior = $derived(!minimo || anterior >= minimo);
	const haySiguiente = $derived(siguiente <= maximo);
</script>

<div class="selector" role="group" aria-label="Mes">
	{#if hayAnterior}
		<a href={enlace(anterior)} aria-label="Mes anterior" data-sveltekit-noscroll><Icono nombre="izquierda" tam={18} /></a>
	{:else}
		<span class="off" aria-hidden="true"><Icono nombre="izquierda" tam={18} /></span>
	{/if}
	<span class="mes">{mesLargo(mes)}</span>
	{#if haySiguiente}
		<a href={enlace(siguiente)} aria-label="Mes siguiente" data-sveltekit-noscroll><Icono nombre="derecha" tam={18} /></a>
	{:else}
		<span class="off" aria-hidden="true"><Icono nombre="derecha" tam={18} /></span>
	{/if}
</div>

<style>
	.selector {
		display: inline-flex;
		align-items: center;
		gap: 2px;
		padding: 3px;
		border-radius: 12px;
		background: var(--superficie);
		border: 1px solid var(--borde);
	}

	a,
	.off {
		display: grid;
		place-items: center;
		width: 34px;
		height: 34px;
		border-radius: 9px;
		color: var(--texto-2);
	}

	a:hover {
		background: var(--superficie-2);
	}

	.off {
		opacity: 0.3;
	}

	.mes {
		min-width: 128px;
		text-align: center;
		font-weight: 650;
		font-size: 0.9rem;
	}
</style>

// app/src/componentes/SelectorMes.tsx
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { mesActual, sumarMeses } from '@/lib/fechas';
import { mesLargo } from '@/lib/formato';
import { useEstilos, useTema } from '@/tema/tema';
import type { Tema } from '@/tema/tokens';
import { Icono } from './Icono';

export function SelectorMes({
	mes,
	minimo,
	maximo = mesActual(),
	onCambio
}: {
	mes: string;
	minimo?: string;
	maximo?: string;
	onCambio: (mes: string) => void;
}) {
	const { c } = useTema();
	const e = useEstilos(estilos);
	const anterior = sumarMeses(mes, -1);
	const siguiente = sumarMeses(mes, 1);
	const hayAnterior = !minimo || anterior >= minimo;
	const haySiguiente = siguiente <= maximo;
	return (
		<View style={e.selector} role="group" aria-label="Mes">
			<Pressable
				role="button"
				aria-label="Mes anterior"
				disabled={!hayAnterior}
				onPress={() => onCambio(anterior)}
				style={[e.flecha, !hayAnterior && e.apagada]}
			>
				<Icono nombre="izquierda" tam={18} color={c.texto2} />
			</Pressable>
			<Text style={e.mes}>{mesLargo(mes)}</Text>
			<Pressable
				role="button"
				aria-label="Mes siguiente"
				disabled={!haySiguiente}
				onPress={() => onCambio(siguiente)}
				style={[e.flecha, !haySiguiente && e.apagada]}
			>
				<Icono nombre="derecha" tam={18} color={c.texto2} />
			</Pressable>
		</View>
	);
}

function estilos({ c }: Tema) {
	return StyleSheet.create({
		selector: {
			flexDirection: 'row',
			alignItems: 'center',
			gap: 2,
			padding: 3,
			borderRadius: 12,
			backgroundColor: c.superficie,
			borderWidth: 1,
			borderColor: c.borde,
			alignSelf: 'flex-start'
		},
		flecha: { width: 34, height: 34, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
		apagada: { opacity: 0.3 },
		mes: { minWidth: 128, textAlign: 'center', fontWeight: '600', fontSize: 14.4, color: c.texto }
	});
}
