// web/src/routes/categorias/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import FilaMovimiento from '$lib/componentes/FilaMovimiento.svelte';
	import GraficoBarras, { type Serie } from '$lib/componentes/GraficoBarras.svelte';
	import Icono from '$lib/componentes/Icono.svelte';
	import Leyenda from '$lib/componentes/Leyenda.svelte';
	import SelectorMes from '$lib/componentes/SelectorMes.svelte';
	import Vacio from '$lib/componentes/Vacio.svelte';
	import { COLOR_OTRAS, colorCategoria, nombreCategoria } from '$lib/categorias';
	import { listaMeses, mesDe, parametroMes } from '$lib/fechas';
	import { clp, mesCorto, mesLargo, porcentaje } from '$lib/formato';

	let { data } = $props();

	const meses = $derived(listaMeses(data.mes, 6));
	const matriz = $derived.by(() => {
		const m = new Map<string, number[]>();
		for (const g of data.gasto) {
			const i = meses.indexOf(mesDe(g.fecha));
			if (i < 0) continue;
			if (!m.has(g.categoria)) m.set(g.categoria, Array(6).fill(0));
			m.get(g.categoria)![i] += g.monto_gasto;
		}
		return m;
	});
	const ordenadas = $derived([...matriz.entries()].sort((a, b) => b[1].reduce((s, x) => s + x, 0) - a[1].reduce((s, x) => s + x, 0)));

	const series = $derived.by((): Serie[] => {
		if (data.cat) {
			return [{ id: data.cat, nombre: nombreCategoria(data.cat), color: colorCategoria(data.cat), valores: matriz.get(data.cat) ?? Array(6).fill(0) }];
		}
		const principales = ordenadas.slice(0, 6);
		const resto = ordenadas.slice(6);
		const s: Serie[] = principales.map(([id, v]) => ({ id, nombre: nombreCategoria(id), color: colorCategoria(id), valores: v }));
		if (resto.length) {
			s.push({ id: 'otras', nombre: 'Otras', color: COLOR_OTRAS, valores: meses.map((_, i) => resto.reduce((t, [, v]) => t + v[i], 0)) });
		}
		return s;
	});

	const delMes = $derived(
		ordenadas
			.map(([id, v]) => ({ id, monto: v[5], previo: v[4], serie: v }))
			.filter((c) => c.monto > 0)
			.sort((a, b) => b.monto - a.monto)
	);
	const totalMes = $derived(delMes.reduce((s, c) => s + c.monto, 0));

	function enlace(params: Record<string, string | null>): string {
		const u = new URLSearchParams({ mes: parametroMes(data.mes) });
		if (data.cat) u.set('cat', data.cat);
		for (const [k, v] of Object.entries(params)) v == null ? u.delete(k) : u.set(k, v);
		return `/categorias?${u}`;
	}
</script>

<svelte:head><title>Categorías · Cuotazo</title></svelte:head>

<div class="pagina">
	<header class="pagina-cabecera">
		<div>
			<h1>Categorías</h1>
			<p class="subtitulo">En qué se va tu plata, mes a mes</p>
		</div>
		<SelectorMes mes={data.mes} />
	</header>

	<section class="tarjeta">
		<div class="tarjeta-cabecera">
			<div>
				<h2>{data.cat ? nombreCategoria(data.cat) : 'Gasto por categoría'}</h2>
				<p class="tenue">Últimos 6 meses · toca un mes para verlo</p>
			</div>
			{#if data.cat}
				<a class="boton fantasma" href={enlace({ cat: null })} data-sveltekit-noscroll><Icono nombre="cerrar" tam={16} /> Todas</a>
			{/if}
		</div>
		{#if ordenadas.length}
			<GraficoBarras
				descripcion="Gasto por categoría en los últimos 6 meses"
				etiquetas={meses.map(mesCorto)}
				titulos={meses.map(mesLargo)}
				{series}
				seleccionado={5}
				onseleccion={(i) => goto(enlace({ mes: parametroMes(meses[i]) }), { noScroll: true })}
				alto={230}
				anchoMaxBarra={56}
			/>
			{#if series.length > 1}<Leyenda items={series} />{/if}
		{:else}
			<Vacio titulo="Sin gastos en estos meses" compacto />
		{/if}
	</section>

	<div class="rejilla" class:rejilla-2={!!data.cat}>
		<section class="tarjeta">
			<div class="tarjeta-cabecera">
				<h2>{mesLargo(data.mes)}</h2>
				<p class="cifra num chica">{clp(totalMes)}</p>
			</div>
			{#if delMes.length}
				<ul class="cats">
					{#each delMes as c (c.id)}
						{@const variacion = c.previo > 0 ? ((c.monto - c.previo) / c.previo) * 100 : null}
						{@const maxSerie = Math.max(...c.serie)}
						<li>
							<a href={enlace({ cat: data.cat === c.id ? null : c.id })} class:activa={data.cat === c.id} data-sveltekit-noscroll>
								<span class="punto" style:background={colorCategoria(c.id)}></span>
								<span class="info">
									<span class="nombre">{nombreCategoria(c.id)}</span>
									<span class="tenue">
										{porcentaje((c.monto / totalMes) * 100)} del mes
										{#if variacion != null}
											· <span class:sube={variacion > 5} class:baja={variacion < -5}>{variacion > 0 ? '+' : ''}{porcentaje(variacion)}</span>
										{/if}
									</span>
								</span>
								<span class="chispa" aria-hidden="true">
									{#each c.serie as v, i (i)}
										<span style:height="{maxSerie ? Math.max(8, (v / maxSerie) * 100) : 8}%" style:background={i === 5 ? colorCategoria(c.id) : undefined}></span>
									{/each}
								</span>
								<span class="num valor">{clp(c.monto)}</span>
							</a>
						</li>
					{/each}
				</ul>
			{:else}
				<Vacio titulo="Sin gastos este mes" compacto />
			{/if}
		</section>

		{#if data.cat}
			<section class="tarjeta">
				<div class="tarjeta-cabecera">
					<div>
						<h2>Movimientos</h2>
						<p class="tenue">{nombreCategoria(data.cat)} · {mesLargo(data.mes)}</p>
					</div>
					<a href="/movimientos?mes={parametroMes(data.mes)}&categoria={data.cat}">Ver en tabla</a>
				</div>
				{#if data.movimientos.length}
					<ul class="movs">
						{#each data.movimientos as m (m.movimiento_id)}
							<FilaMovimiento {m} conFecha />
						{/each}
					</ul>
				{:else}
					<Vacio titulo="Sin movimientos" compacto>No hay movimientos de esta categoría en el mes.</Vacio>
				{/if}
			</section>
		{/if}
	</div>
</div>

<style>
	.chica {
		font-size: 1.15rem;
	}

	.cats,
	.movs {
		list-style: none;
		margin: 0;
		padding: 0;
	}

	.cats a {
		display: flex;
		align-items: center;
		gap: 12px;
		padding: 11px 10px;
		margin: 0 -10px;
		border-radius: 12px;
		color: inherit;
	}

	.cats a:hover {
		background: var(--superficie-2);
	}

	.cats a.activa {
		background: var(--acento-suave);
	}

	.info {
		flex: 1;
		min-width: 0;
		display: flex;
		flex-direction: column;
	}

	.nombre {
		font-weight: 600;
		font-size: 0.92rem;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.info .tenue {
		font-size: 0.76rem;
	}

	.sube {
		color: var(--negativo);
		font-weight: 600;
	}

	.baja {
		color: var(--positivo);
		font-weight: 600;
	}

	.chispa {
		display: flex;
		align-items: flex-end;
		gap: 2px;
		height: 24px;
		width: 44px;
		flex: none;
	}

	.chispa span {
		flex: 1;
		border-radius: 2px 2px 0 0;
		background: var(--superficie-3);
	}

	.valor {
		font-weight: 650;
		font-size: 0.92rem;
		min-width: 86px;
		text-align: right;
	}
</style>

// app/src/app/(app)/categorias.tsx
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import Svg, { Rect } from 'react-native-svg';
import { Boton, CabeceraTarjeta, EnlaceCabecera, Punto, Rejilla, Tarjeta, Vacio } from '@/componentes/base';
import { FilaMovimiento } from '@/componentes/FilaMovimiento';
import { GraficoBarras, type Serie } from '@/componentes/GraficoBarras';
import { Leyenda } from '@/componentes/Leyenda';
import { Pagina } from '@/componentes/Pagina';
import { SelectorMes } from '@/componentes/SelectorMes';
import { useCarga } from '@/datos/carga';
import { useFuente } from '@/datos/sesion';
import { nombreCategoria } from '@/lib/categorias';
import { finDeMes, listaMeses, mesDe, parametroMes, sumarMeses } from '@/lib/fechas';
import { clp, mesCorto, mesLargo, porcentaje } from '@/lib/formato';
import { useParamMes } from '@/lib/rutas';
import { comunes } from '@/tema/comunes';
import { useEstilos, useTema } from '@/tema/tema';
import { NUMEROS, type Tema } from '@/tema/tokens';

// Minigráfico de 6 meses; el último en el color de la categoría
function Minigrafico({ serie, color, apagado }: { serie: number[]; color: string; apagado: string }) {
	const max = Math.max(...serie);
	const ancho = 44;
	const alto = 24;
	const w = (ancho - 2 * (serie.length - 1)) / serie.length;
	return (
		<Svg width={ancho} height={alto} aria-hidden>
			{serie.map((v, i) => {
				const h = alto * (max ? Math.max(0.08, v / max) : 0.08);
				return <Rect key={i} x={i * (w + 2)} y={alto - h} width={w} height={h} rx={1.5} fill={i === serie.length - 1 ? color : apagado} />;
			})}
		</Svg>
	);
}

export default function Categorias() {
	const [mes, cambiarMes] = useParamMes();
	const { cat: catParam } = useLocalSearchParams<{ cat?: string }>();
	const cat = typeof catParam === 'string' && catParam ? catParam : null;
	const d = useFuente();
	const t = useTema();
	const e = useEstilos(estilos);
	const k = useEstilos(comunes);

	const carga = useCarga(async () => {
		const [gasto, detalle] = await Promise.all([
			d.gastoDiario(sumarMeses(mes, -5), finDeMes(mes)),
			cat ? d.movimientos({ categoria: cat, desde: mes, hasta: finDeMes(mes) }) : Promise.resolve(null)
		]);
		return { mes, cat, gasto, movimientos: detalle?.filas ?? [] };
	}, [d, mes, cat]);
	const data = carga.datos;

	const calculo = useMemo(() => {
		if (!data) return null;
		const meses = listaMeses(data.mes, 6);
		const matriz = new Map<string, number[]>();
		for (const g of data.gasto) {
			const i = meses.indexOf(mesDe(g.fecha));
			if (i < 0) continue;
			if (!matriz.has(g.categoria)) matriz.set(g.categoria, Array(6).fill(0));
			matriz.get(g.categoria)![i] += g.monto_gasto;
		}
		const suma = (v: number[]) => v.reduce((s, x) => s + x, 0);
		const ordenadas = [...matriz.entries()].sort((a, b) => suma(b[1]) - suma(a[1]));
		let series: Serie[];
		if (data.cat) {
			series = [{ id: data.cat, nombre: nombreCategoria(data.cat), color: t.cat(data.cat), valores: matriz.get(data.cat) ?? Array(6).fill(0) }];
		} else {
			const resto = ordenadas.slice(6);
			series = ordenadas.slice(0, 6).map(([id, v]) => ({ id, nombre: nombreCategoria(id), color: t.cat(id), valores: v }));
			if (resto.length) series.push({ id: 'otras', nombre: 'Otras', color: t.otras, valores: meses.map((_, i) => resto.reduce((s, [, v]) => s + v[i], 0)) });
		}
		const delMes = ordenadas
			.map(([id, v]) => ({ id, monto: v[5], previo: v[4], serie: v }))
			.filter((x) => x.monto > 0)
			.sort((a, b) => b.monto - a.monto);
		return { meses, ordenadas, series, delMes, totalMes: delMes.reduce((s, x) => s + x.monto, 0) };
	}, [data, t]);

	const cambiarCat = (c: string | null) => router.setParams({ cat: c ?? undefined });
	const cabecera = { titulo: 'Categorías', subtitulo: 'En qué se va tu plata, mes a mes', derecha: <SelectorMes mes={mes} onCambio={cambiarMes} /> };
	if (!data || !calculo) return <Pagina {...cabecera} sinDatos={!carga.error} error={carga.error} onReintentar={carga.recargar} />;
	const { meses, ordenadas, series, delMes, totalMes } = calculo;

	return (
		<Pagina {...cabecera} cargando={carga.cargando} onReintentar={carga.recargar}>
			<Tarjeta>
				<CabeceraTarjeta
					titulo={data.cat ? nombreCategoria(data.cat) : 'Gasto por categoría'}
					subtitulo="Últimos 6 meses · toca un mes para verlo"
					derecha={data.cat ? <Boton variante="fantasma" icono="cerrar" texto="Todas" onPress={() => cambiarCat(null)} /> : null}
				/>
				{ordenadas.length ? (
					<>
						<GraficoBarras
							descripcion="Gasto por categoría en los últimos 6 meses"
							etiquetas={meses.map(mesCorto)}
							titulos={meses.map(mesLargo)}
							series={series}
							seleccionado={5}
							onSeleccion={(i) => cambiarMes(meses[i])}
							alto={230}
							anchoMaxBarra={56}
						/>
						{series.length > 1 ? <Leyenda items={series} /> : null}
					</>
				) : (
					<Vacio titulo="Sin gastos en estos meses" compacto />
				)}
			</Tarjeta>

			<Rejilla columnas={data.cat ? 2 : 1}>
				<Tarjeta estilo={{ flexGrow: 1 }}>
					<CabeceraTarjeta titulo={mesLargo(data.mes)} derecha={<Text style={[k.cifra, { fontSize: 18.4 }]}>{clp(totalMes)}</Text>} />
					{delMes.length ? (
						<View role="list">
							{delMes.map((x) => {
								const variacion = x.previo > 0 ? ((x.monto - x.previo) / x.previo) * 100 : null;
								const activa = data.cat === x.id;
								return (
									<Pressable
										key={x.id}
										role="button"
										aria-pressed={activa}
										onPress={() => cambiarCat(activa ? null : x.id)}
										style={[e.cat, activa && { backgroundColor: t.c.acentoSuave }]}
									>
										<Punto color={t.cat(x.id)} />
										<View style={{ flex: 1, minWidth: 0 }}>
											<Text style={e.nombre} numberOfLines={1}>
												{nombreCategoria(x.id)}
											</Text>
											<Text style={e.sub}>
												{porcentaje((x.monto / totalMes) * 100)} del mes
												{variacion != null ? (
													<Text>
														{' · '}
														<Text style={variacion > 5 ? e.sube : variacion < -5 ? e.baja : null}>
															{variacion > 0 ? '+' : ''}
															{porcentaje(variacion)}
														</Text>
													</Text>
												) : null}
											</Text>
										</View>
										<Minigrafico serie={x.serie} color={t.cat(x.id)} apagado={t.c.superficie3} />
										<Text style={e.valor}>{clp(x.monto)}</Text>
									</Pressable>
								);
							})}
						</View>
					) : (
						<Vacio titulo="Sin gastos este mes" compacto />
					)}
				</Tarjeta>

				{data.cat ? (
					<Tarjeta estilo={{ flexGrow: 1 }}>
						<CabeceraTarjeta
							titulo="Movimientos"
							subtitulo={`${nombreCategoria(data.cat)} · ${mesLargo(data.mes)}`}
							derecha={<EnlaceCabecera href={{ pathname: '/movimientos', params: { mes: parametroMes(data.mes), categoria: data.cat } }} texto="Ver en tabla" />}
						/>
						{data.movimientos.length ? (
							<View role="list">
								{data.movimientos.map((m, i) => (
									<FilaMovimiento key={m.movimiento_id} m={m} conFecha ultima={i === data.movimientos.length - 1} />
								))}
							</View>
						) : (
							<Vacio titulo="Sin movimientos" compacto>
								No hay movimientos de esta categoría en el mes.
							</Vacio>
						)}
					</Tarjeta>
				) : null}
			</Rejilla>
		</Pagina>
	);
}

function estilos({ c }: Tema) {
	return StyleSheet.create({
		cat: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 11, paddingHorizontal: 10, marginHorizontal: -10, borderRadius: 12 },
		nombre: { fontWeight: '600', fontSize: 14.7, color: c.texto },
		sub: { fontSize: 12.2, color: c.texto3 },
		sube: { color: c.negativo, fontWeight: '600' },
		baja: { color: c.positivo, fontWeight: '600' },
		valor: { fontWeight: '600', fontSize: 14.7, minWidth: 86, textAlign: 'right', color: c.texto, fontVariant: NUMEROS }
	});
}
